### ISSUE TITLE
ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by vairamsvsjdo** [HelioGuilherme66/robotframework-selenium2library#12]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Selenium2Library
- [ ] This is not a usage question (Those should be directed to the 
      [google groups](http://groups.google.com/group/robotframework-users/) or 
      [slack chat](https://robotframework-slack.herokuapp.com/))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. _downloaded and installed using pip setup.py install command from this fork. 
2. _ ran a simple test case that does Log    hello world 
3. _

## Expected behavior and actual behavior

When I follow those steps, I see...
The script executes successfully. But also receive the following error.
ModuleNotFoundError: No module named 'future'
I was expecting...
the script to run successfully without error. 
## Environment

Browsers

- [ ] Internet Explorer (version:      )
- [ ] Google Chrome     (version:      )
- [x ] Mozilla Firefox   (version:   latest   )
- [ ] Opera             (version:      )
- [ ] PhantomJS         (version:      )
- [ ] Safari (Mac OS X) (version:      )

Operating System

- [x ] Windows  (version:      )
- [ ] Mac OS X (version:      )
- [ ] Linux    (version:     distro:              )

Libraries

- Robot Framework version:
- Selenium version: 3.3.3
- Selenium2Library ([x] Python or [ ] Jython) version:1.8.0b1

## Isolating and demonstrating the problem

- [ ] This bug happens when testing a public site: [example](http://example.org/)
- [ ] The bug happens consistently across all tested browsers
- [ ] The Robot Framework Test file or snippet is attached or
      at [some public site](http://pastebin.com/)
- x[ ] The Test was called from: [x ] Local machine   [ ] Remote Automation (Jenkins CI)

**Comment by leorush** [comment]
Did you installed future library? 
run this:
`pip3 install future`

**Comment by vairamsvsjdo** [comment]
That resolved the issue. Thanks

**Comment by vairamsvsjdo** [comment]
Is it possible to add this as a dependency requirement to pull automatically?

**Comment by HelioGuilherme66** [comment]
In the future we will not need future ;)
That import is there because of Python 2.7, and we will stop using that.
Since this fork/branch was a workaround for Python 3.x, and we will have the original project fixed (soon), we do not need to have developments here.

**Comment by vairamsvsjdo** [comment]
G8:)
Thanks
